name: build dev
on: [workflow_dispatch]

jobs:

  build_app:
    runs-on: ubuntu-22.04
    outputs:
      image_tag: ${{ steps.gen_tags.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set global env
        id: global_env
        run: |
          echo "::set-output name=DOCKERHUB_IMAGE_NAME::registry.vaulterix.ru/dev/collabora"

      - name: Generate tags
        id: gen_tags
        run: |
          echo ::set-output name=tag::$(echo ${GITHUB_REF:10})

      - name: Build and tag image
        run: |
          docker build -f docker/from-source-gh-action/Dockerfile -t "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{steps.gen_tags.outputs.tag}}" .

      - name: Docker login
        run: docker login registry.vaulterix.ru -u ${{secrets.new_registry_user}} -p ${{secrets.new_registry_password}}

      - name: Publish image
        env:
          IMAGE_NAME: $GITHUB_REPOSITORY
        run: docker push "${{ steps.global_env.outputs.DOCKERHUB_IMAGE_NAME }}:${{steps.gen_tags.outputs.tag}}"
